// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function ScanDir(arg1:string):Promise<main.ScanDirJSON>;

export function UpdateConfig(arg1:config.Config,arg2:boolean):Promise<config.Config>;
